require('dotenv').config();
const express = require('express');
const cors = require('cors');
const { OpenAI } = require('openai');

const app = express();
const PORT = process.env.PORT || 4000;

app.use(cors());
app.use(express.json({ limit: '10mb' })); // Support large image payloads

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

const getRandomPair = (arr) => {
  if (arr.length < 2) return arr;
  const shuffled = arr.slice().sort(() => 0.5 - Math.random());
  return [shuffled[0], shuffled[1]];
};

// POST /analyze: expects { image: <base64 string> }
app.post('/analyze', async (req, res) => {
  const { image } = req.body;
  if (!image) {
    return res.status(400).json({ error: 'No image provided' });
  }
  const openaiApiKey = process.env.OPENAI_API_KEY;
  if (!openaiApiKey) {
    return res.status(500).json({ error: 'OpenAI API key not configured' });
  }
  console.log('Received image for analysis (length):', image.length);

  try {
    // Prepare the prompt for object detection
    const prompt = `List all MOVABLE objects you see in this image. For each object, provide a short name and a confidence score from 0 to 1. Return the result as a JSON array of objects with 'name' and 'confidence' fields. Only include objects that a person could reasonably pick up and move.`;

    // Call OpenAI Vision API (GPT-4 Turbo with vision)
    const response = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        {
          role: 'user',
          content: [
            { type: 'text', text: prompt },
            { type: 'image_url', image_url: { url: image } },
          ],
        },
      ],
      max_tokens: 500,
    });

    // Parse the response
    const text = response.choices[0]?.message?.content;
    let objects = [];
    try {
      // Try to extract the JSON array from the response
      const match = text.match(/\[.*\]/s);
      if (match) {
        objects = JSON.parse(match[0]);
      } else {
        objects = [];
      }
    } catch (err) {
      console.error('Failed to parse OpenAI response:', err, text);
      objects = [];
    }

    res.json({ objects, message: 'OpenAI Vision API result.' });
  } catch (err) {
    console.error('OpenAI Vision API error:', err);
    res.status(500).json({ error: 'Failed to analyze image with OpenAI Vision API.' });
  }
});

// POST /generate-task: expects { objects: [<string>] }
app.post('/generate-task', async (req, res) => {
  const { objects } = req.body;
  if (!objects || !Array.isArray(objects) || objects.length < 2) {
    return res.status(400).json({ error: 'At least two objects are required to generate a task.' });
  }
  const openaiApiKey = process.env.OPENAI_API_KEY;
  if (!openaiApiKey) {
    return res.status(500).json({ error: 'OpenAI API key not configured' });
  }
  // Pick two random objects
  const [obj1, obj2] = getRandomPair(objects);
  try {
    const prompt = `You are a creative game designer. Given the following two real-world objects: ${obj1} and ${obj2}, write a fun and challenging forging task for a scavenger hunt game. The task should require the player to combine these two objects to create a new, imaginative object, but DO NOT reveal the solution or which objects to combine in the description. Only provide a short, engaging description of the challenge (e.g., 'Forge something that can scoop water.'). Respond ONLY with the description as a string.`;

    const response = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        { role: 'user', content: prompt },
      ],
      max_tokens: 120,
    });
    const description = response.choices[0]?.message?.content?.trim();
    if (!description) {
      return res.status(500).json({ error: 'No task description generated.' });
    }
    // Compose the task object
    const task = {
      id: `task-${Date.now()}`,
      description,
      requirements: [obj1, obj2],
      solved: false,
      solutionHint: `Debug: Combine '${obj1}' and '${obj2}' to solve this task.`
    };
    res.json({ task, message: 'Task generated by OpenAI LLM.' });
  } catch (err) {
    console.error('OpenAI LLM error (task generation):', err);
    res.status(500).json({ error: 'Failed to generate task with OpenAI LLM.' });
  }
});

app.listen(PORT, '0.0.0.0', () => {
  console.log(`Server running on http://0.0.0.0:${PORT}`);
}); 